### ISSUE TITLE
As a Open Data Hub Manager I would like to have the SkyAlps data exported in the GTFS format, so to import them in the Open Trip Planner

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-elaborations#18]
- [x] create repository by @dulvui (suggest under https://github.com/noi-techpark/bdp-elaborations) 
- [x] PR by Gruppo FOS
- [x] deployment by @dulvui 
- [x] testing by @rcavaliere 
- [x] put on production
- [ ] [to be discussed] on-demand GTFS export generation service on the Open Data Hub website?

**Comment by rcavaliere** [comment]
@dulvui please try to have a look at the work of Gruppo FOS and deploy this application - see https://github.com/noi-techpark/bdp-elaborations/pull/20

**Comment by dulvui** [comment]
@rcavaliere I merged now and will create the test deployment now.

**Comment by rcavaliere** [comment]
@dulvui can you please give some priority to this task in the next sprint? I know the issue here with the supplier, but we would like to close this in reasonable short times.

**Comment by dulvui** [comment]
@rcavaliere Okay, I will gibe it more priority. I will try to finish the s3 bucket upload this afternoon

**Comment by dulvui** [comment]
@rcavaliere It works now also with S3 bucket upload. I configured a scheduler that uploads every day at midnight 24:00 the files to and S3 bucket.
Here a example of the Routes.txt file https://flighdata-skyalps-gtfs-test.s3.eu-west-1.amazonaws.com/Routes.txt
Lets check together on Monday if everything is fine and if other things are missing.

**Comment by rcavaliere** [comment]
@dulvui I have started to test this, but there are a lot of mistakes / missing things with respect of what we specified. I will prepare a detailed summary mail to the supplier

**Comment by dulvui** [comment]
@rcavaliere I was now able to merge the new PR and the changes are live in testing. The files are already updated by the new version on the S3 bucket.
Can you please check if the files are correct now?

**Comment by rcavaliere** [comment]
@dulvui thanks! I will test them in the next days, probably on Friday

**Comment by rcavaliere** [comment]
@dulvui new testing session completed, better but still with issues. Wait for new PR by SkyAlps fixing these last points.

**Comment by rcavaliere** [comment]
@dulvui 3rd PR available: https://github.com/noi-techpark/bdp-elaborations/pull/26 please integrate it and hope that all remaining issues are solved, I will further test this.

I think we need to discuss tomorrow how to make the GTFS data available, the common way is a ZIP file. In my opinion this elaboration can be triggered every day, and every day a new GTFS export is produced (with a different file name, which includes the data, e.g. "2023-04-27_SkyAlps_GTFS.zip")

**Comment by ohnewein** [comment]
Providing a ZIP File in some way breaks the concept of "API first" of the Open Data Hub.

Is there really no way to handle this over API calls?

**Comment by rcavaliere** [comment]
@dulvui testing completed, please put on production (once the user story https://github.com/noi-techpark/it.bz.opendatahub.api.mobility-ninja/issues/32 is implemented)
