### ISSUE TITLE
Parking "free" elaboration does not work

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-elaborations#22]
This elaboration seems to be somehow stopped, needs to be reactivated again!

![Screenshot from 2023-04-14 06-19-50](https://user-images.githubusercontent.com/9825179/231940900-aee8ce56-ad0b-44fd-b140-cb03dbe368bc.png)

**Comment by clezag** [comment]
There was an issue where the writer API URL ended with a slash, but in the elaboration itself, another slash was appended, resulting in a double slash.
While technically a valid URL, the writer API, or more specifically spring, does block these URL to avoid unintended behavior.

The reason why this issue only came up now, is that the old Apache proxy seems to have silently normalized the URL before proxying it, while the new Caddy proxy we've recently migrated the writer API to does not.

@rcavaliere I've released a fix in production, to me it looks like it's OK now. The same issue was present in the a22 environment non linear calibration elaboration.
