### ISSUE TITLE
As an AI expert, I would like that the Open Data Hub provides simple traffic elaborations, so that I can use them to automatically check the data quality available and consider it in the automatic computations

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-elaborations#29]
CISMA and u-hopper would need to have prepared daily statistics of the traffic volumes so to simplify their controls on the data quality of the different traffic stations. This would also be an added value for 3rd parties willing to use more simple and compact elaborated data. The elaborations to be automatically computed should be the following:
- [ ] for each station: nr. buses, nr. heavy vehicles and nr. light vehicles with additional period = 86400 (should be the sum of all the records of the day related to these data types); total_nr_vehicles = nr. buses + nr. heavy vehicles + nr. light vehicles
- [ ] create new "virtual stations" that are father of some existing traffic stations. These virtual stations should group all the traffic stations having the same direction of travel "e.g. corsia di marcia sud + corsia di sorpasso sud". The types to be considered are just those of the previous point, and they are just the sum of the corresponding data from the two stations

Regarding the naming of these new virtual stations: it should just be e.g. SEZIONE DI RILEVAMENTO KM 107.0 - S.FLORIANO (direzione sud) [no reference to the direction of travel]

**Comment by clezag** [comment]
@rcavaliere Not sure if I understood this right. We have to aggregate each single data type to the period of 1 day, and then also sum up the total number of vehicles, or is only the total needed and not per single vehicle type?

**Comment by rcavaliere** [comment]
@clezag we need the single totals per vehicle type, and also the total! Just these categories: nr. buses, nr. heavy vehicles and nr. light vehicles (should be the sum of all the records of the day related to these data types). Plus: total_nr_vehicles = nr. buses + nr. heavy vehicles + nr. light vehicles

**Comment by clezag** [comment]
@rcavaliere everything OK then, just what I implemented. I've got the single data type sums running in testing now, working on the total and combining stations

**Comment by clezag** [comment]
@rcavaliere For the virtual stations, do they have the same station type as children (TrafficSensor), or do we make them something like CombinedTrafficSensor?

**Comment by rcavaliere** [comment]
@clezag I would leave the same stationType. We have the parentID field in order to differentiate the different type of stations

**Comment by rcavaliere** [comment]
@clezag very good work!
 The type "Nr. Equivalent Vehicles" is a particular elaboration that weights in a different way the heavy vehicles w.r.t. to light vehicles, there is a particular formula to be applied. Let me check with CISMA if we need also this kind of elaboration for such an aggregation. For the rest, it looks everything OK.  For inactive stations do you mean "active = FALSE" or did you consider any other critieria?

**Comment by clezag** [comment]
@rcavaliere yes, I'm just checking for the active flag when requesting stations to elaborate.

**Comment by rcavaliere** [comment]
@clezag as separately discussed with CISMA, let's add this additional elaboration related to the Nr. Equivalent Vehicles, calculated as follows Nr. Light Vehicles + 2.5*Nr. Heavy Vehicles + 2.5*Nr. Buses

**Comment by clezag** [comment]
@rcavaliere already done. I've summed up all the Equivalent Vehicles instead of applying the formula again, but from the checks I've done it looks correct.

I've extracted this data directly from the DB, the last two columns are the total and equiv calculated in SQL as a check
[check.csv](https://github.com/noi-techpark/bdp-elaborations/files/14341680/check.csv)

**Comment by clezag** [comment]
@rcavaliere Released in production
