### ISSUE TITLE
As SkyAlps I would like to convert the currently available GTFS export in NeTEx, so that this data can be integrated in the Italian National Access Point and be used by national MaaS Operators

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-elaborations#37]
At national level there are GTFS converters that can convert GTFS exports in NeTEx, ensuring the compliance with the Italian specifications. In order to use one of them and produce the requested NeTEx export also for the SkyAlps dataset, we need to fix the GTFS export as follows:

- we need to add the `feed_info.txt` file (see https://gtfs.org/schedule/reference/). Many fields can be copied from the already existing `agency.txt` file
- we need to add the `shapes.txt` file containing mainly the distances between start / destination couples. This could be automatically calculated by considering in input the coordinates of the airports considered. 
- the existing file `trips.txt`  has to include the field `shape_id`, i.e. the reference to the `shapes.txt` file
- the existing file `stop_times.txt` has to include the field `shape_dist_traveled`, i.e. the distance between two consecutive stops. Must be consistent with the distances provided in the `shapes.txt` file.

Activities to do:
- [x] Specify how the additional fields requested have to be populated.
- [x] Implement a module that integrates the additional parts to the GTFS exports (or integrate all this in the module that automatically generates the GTFS export)

**Comment by clezag** [comment]
@rcavaliere now up in testing. 
https://flighdata-skyalps-gtfs-test.s3.eu-west-1.amazonaws.com/GTFS.zip

**Comment by rcavaliere** [comment]
@clezag very good, I will test it and let you know in case we need some adaptations

**Comment by rcavaliere** [comment]
@clezag seems to be OK, the only thing which I think is not correctly implemented is in my view the `shape_id`, which is equivalent to the `route_id`. And why we have multiple records for each shape_id? We should have maximum two records per `shape_id` in the `shapes.txt` file.

**Comment by clezag** [comment]
@rcavaliere good catch! 
Fixed now in testing

**Comment by rcavaliere** [comment]
@clezag I refer to what I see on that link: https://flighdata-skyalps-gtfs-test.s3.eu-west-1.amazonaws.com/GTFS.zip (see above your post).
There are some cosmetic things to fix to ensure full GTFS compliance:

- [ ] correct file of shape file is "`shapes.txt`", not "shape.txt"
- [ ] in the first row of "shapes.txt" there is a space before the record " `shape_id,shape_pt_lat,shape_pt_lon,shape_pt_sequence,shape_dist_traveled`". Please remove it.
- [ ] the values in `dist_traveled` should be provided in meters, not in kilometers.

Can you please fix all this? Thanks!
